#!/bin/bash
# Quick reference guide after computer restart

echo "========================================"
echo "GENERALS.IO DRL PROJECT - QUICK START"
echo "========================================"
echo ""
echo "📍 Location: /Users/sujithjulakanti/Desktop/DRL Project"
echo ""
echo "▶️  STEP 1: Download 50k replays"
echo "   Option A (simple):"
echo "     python download_50k.py"
echo ""
echo "   Option B (with arguments):"
echo "     python src/preprocessing/download_replays.py --output_dir data/raw --num_replays 50000"
echo ""
echo "   ⚡ Quick test (100 replays):"
echo "     python download_50k.py  # Edit NUM_REPLAYS = 100 first"
echo ""
echo "▶️  STEP 2: Preprocess replays"
echo "   python src/preprocessing/preprocess_replays.py"
echo ""
echo "▶️  STEP 3: Train with Behavior Cloning"
echo "   python src/training/train_bc.py"
echo ""
echo "▶️  STEP 4: Evaluate"
echo "   python src/evaluation/evaluate.py"
echo ""
echo "========================================"
echo "📊 EXPECTED TIMELINE"
echo "========================================"
echo "  Download:    2-4 hours (50k replays)"
echo "  Preprocess:  2-3 hours"
echo "  BC Training: ~18 hours"
echo "  Total:       ~24 hours"
echo ""
echo "⚙️  System: MacBook M4 Air with MPS (Apple Silicon)"
echo ""
echo "========================================"
echo "🔍 CHECK STATUS"
echo "========================================"
echo "  ls -lh data/raw/train/  # Check downloaded files"
echo "  ls -lh data/processed/  # Check preprocessed data"
echo "  ls -lh checkpoints/     # Check training progress"
echo ""
