#!/bin/bash
# Quick reference for common commands

echo "==================================================================="
echo "🎮 Generals.io DRL Agent - Command Reference"
echo "==================================================================="
echo ""
echo "📚 DOCUMENTATION"
echo "  Main guide:      COMPLETE_PROJECT_GUIDE.md"
echo "  DQN training:    DQN_TRAINING_GUIDE.md"
echo "  Research paper:  DQN_IMPLEMENTATION_GUIDE.md"
echo "  BC results:      EVALUATION_RESULTS.md"
echo ""
echo "==================================================================="
echo "🚀 TRAINING"
echo "==================================================================="
echo ""
echo "  # BC Training (already complete! ✅)"
echo "  python3 src/training/train_bc.py"
echo ""
echo "  # DQN Training - Quick test (3 minutes)"
echo "  ./train_dqn.sh 0.05"
echo ""
echo "  # DQN Training - Short (2 hours)"
echo "  ./train_dqn.sh 2"
echo ""
echo "  # DQN Training - Full (6 hours) ⭐ RECOMMENDED"
echo "  ./train_dqn.sh 6"
echo ""
echo "==================================================================="
echo "📊 EVALUATION"
echo "==================================================================="
echo ""
echo "  # Evaluate BC model"
echo "  python3 src/evaluation/evaluate.py \\"
echo "    --model_path checkpoints/bc/best_model.pt \\"
echo "    --test_dir data/processed/test \\"
echo "    --output_file results/bc_evaluation.json"
echo ""
echo "  # Evaluate DQN model (after training)"
echo "  python3 src/evaluation/evaluate.py \\"
echo "    --model_path checkpoints/dqn/best_model.pt \\"
echo "    --test_dir data/processed/test \\"
echo "    --output_file results/dqn_evaluation.json"
echo ""
echo "==================================================================="
echo "📈 MONITORING"
echo "==================================================================="
echo ""
echo "  # View BC training logs"
echo "  tensorboard --logdir logs/bc"
echo ""
echo "  # View DQN training logs"
echo "  tensorboard --logdir logs/dqn_self_play"
echo ""
echo "  # Check training status"
echo "  python3 check_training.py"
echo ""
echo "==================================================================="
echo "📁 RESULTS"
echo "==================================================================="
echo ""
echo "  # BC model (trained ✅)"
echo "  checkpoints/bc/best_model.pt"
echo "  results/bc_evaluation.json"
echo ""
echo "  # DQN model (train with ./train_dqn.sh)"
echo "  checkpoints/dqn/best_model.pt"
echo "  checkpoints/dqn/training_summary.json"
echo ""
echo "==================================================================="
echo "🔍 DATA"
echo "==================================================================="
echo ""
echo "  # Training data: 39,065 examples"
echo "  data/processed/train/data.npz"
echo ""
echo "  # Validation data: 4,772 examples"
echo "  data/processed/val/data.npz"
echo ""
echo "  # Test data: 4,886 examples"
echo "  data/processed/test/data.npz"
echo ""
echo "==================================================================="
echo "⚙️  CONFIGURATION"
echo "==================================================================="
echo ""
echo "  Edit parameters: src/config.py"
echo ""
echo "  Key DQN parameters:"
echo "    DQN_LEARNING_RATE = 1e-4"
echo "    DQN_BATCH_SIZE = 128"
echo "    DQN_BUFFER_SIZE = 100000"
echo "    EPSILON_START = 1.0"
echo "    EPSILON_DECAY = 0.999"
echo ""
echo "==================================================================="
echo "📊 CURRENT STATUS"
echo "==================================================================="
echo ""
echo "  Phase 1 - BC Training:       ✅ COMPLETE"
echo "    - Test accuracy: 27.75%"
echo "    - Valid actions: 100%"
echo "    - Estimated Elo: ~1874"
echo ""
echo "  Phase 2 - DQN Training:      ⏸️  READY TO START"
echo "    - Expected accuracy: 32-35%"
echo "    - Expected Elo: ~2000"
echo "    - Duration: 6 hours"
echo ""
echo "  Next step: ./train_dqn.sh 6"
echo ""
echo "==================================================================="
